# Generated by Django 3.1.6 on 2021-05-22 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0017_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='ArticleLike',
        ),
    ]
